import { Check, Circle, ListChecks, CalendarDays, FileText, MessageSquareText } from 'lucide-react';
import { SectionHeading } from './UI';
const benefits = [
  { icon: ListChecks, title: 'Персональный чек-лист', text: 'Список сведений и документов, которые рекомендуется подготовить к встрече.' },
  { icon: CalendarDays, title: 'Хронология событий', text: 'Основные события располагаются в понятной последовательности.' },
  { icon: FileText, title: 'Структурированное описание ситуации', text: 'Вместо разрозненного рассказа формируется краткая карточка обращения.' },
  { icon: MessageSquareText, title: 'Список вопросов', text: 'Заранее сформулируйте, что именно хотите обсудить с адвокатом.' },
];
export default function ResultSection() {
  return <section className="section result-section" id="result"><div className="container result-grid"><div><SectionHeading number="04" eyebrow="Из деталей — в целую картину" title="Результат подготовки" /><div className="benefits">{benefits.map(({ icon: Icon, title, text }) => <div className="benefit" key={title}><span className="icon-box"><Icon size={20} aria-hidden="true" /></span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></div><div className="result-visual"><div className="document-card"><div className="document-top"><span className="document-logo"><FileText size={18} aria-hidden="true" />Карточка обращения</span><span className="demo-label">Демонстрационный пример</span></div><div className="document-title"><span>Подготовка к первой встрече</span><h3>Каждое событие.<br />На своём месте.</h3></div><dl className="document-meta"><div><dt>Направление</dt><dd>ДТП</dd></div><div><dt>Дата события</dt><dd>12 сентября</dd></div><div><dt>Цель обращения</dt><dd>Консультация</dd></div></dl><div className="document-section"><h4>Документы</h4><ul>{['Протокол', 'Фотографии', 'Постановление', 'Медицинские документы'].map((doc, i) => <li key={doc}>{i < 3 ? <Check size={15} aria-hidden="true" /> : <Circle size={12} aria-hidden="true" />}<span>{doc}</span>{i === 3 && <small>Подготовить</small>}</li>)}</ul></div><div className="document-section timeline-section"><h4>Хронология</h4><ol>{[['12.09', 'Произошло ДТП'], ['12.09', 'Составлен протокол'], ['15.09', 'Получено постановление']].map(([date, text]) => <li key={text}><time>{date}</time><span>{text}</span></li>)}</ol></div><div className="document-bottom">Только пример. Реальных пользовательских данных нет.</div></div><span className="result-side-label" aria-hidden="true">ПОДГОТОВЛЕНО ДО ВСТРЕЧИ</span></div></div></section>;
}
